
export const allProducts = [
    {
        products: [
            {
                name: 'Product 1',
                id: 'tier-freelancer',
                type: "year",
                price: "144,299",
                productId: "price_1Ok8ePFxRasdpkclpBCdeUrr",
                description: 'The essentials to provide your best work for clients.',
                features: ['5 products', 'Up to 1,000 subscribers', 'Basic analytics', '48-hour support response time'],
                featured: false,
                active: true,
                cta: 'Buy plan',
            },
            {
                name: 'Product 2',
                id: 'tier-startup',
                type: "year",
                price: "6000",
                productId: "price_1Ok8d3FxRasdpkclQCokDqHN",
                description: 'A plan that scales with your rapidly growing business.',
                features: [
                    '25 products',
                    'Up to 10,000 subscribers',
                    'Advanced analytics',
                    '24-hour support response time',
                    'Marketing automations',
                ],
                featured: false,
                active: true,
                cta: 'Buy plan',
            },
            // {
            //     name: 'Enterprise',
            //     id: 'tier-enterprise',
            //     type: "year",
            //     price: "338,99",
            //     productId: "price_1Ntf2rERe59VaHatWdhX4Y3S",
            //     description: 'Dedicated support and infrastructure for your company.',
            //     features: [
            //         'Unlimited products',
            //         'Unlimited subscribers',
            //         'Advanced analytics',
            //         '1-hour, dedicated support response time',
            //         'Marketing automations',
            //         'Custom reporting tools',
            //     ],
            //     featured: true,
            //     active: false,
            //     cta: 'Buy plan',
            // },
        ],
    },
    {
        products: [
            {
                name: 'Product 1',
                id: 'tier-freelancer',
                type: "month",
                price: "2000",
                productId: "price_1Ok53bFxRasdpkclffy8Sdl8",
                description: 'The essentials to provide your best work for clients.',
                features: ['5 products', 'Up to 1,000 subscribers', 'Basic analytics', '48-hour support response time'],
                featured: false,
                active: true,
                cta: 'Buy plan',
            },
            {
                name: 'Product 2',
                id: 'tier-startup',
                type: "month",
                price: "3000",
                productId: "price_1Ok55xFxRasdpkclojO6S32B",
                description: 'A plan that scales with your rapidly growing business.',

                features: [
                    '25 products',
                    'Up to 10,000 subscribers',
                    'Advanced analytics',
                    '24-hour support response time',
                    'Marketing automations',
                ],
                featured: false,
                active: true,
                cta: 'Buy plan',
            },
            // {
            //     name: 'Enterprise',
            //     id: 'tier-enterprise',
            //     price: "34,99",
            //     productId: "price_1Ntf2rERe59VaHatWdhX4Y3S",
            //     description: 'Dedicated support and infrastructure for your company.',
            //     features: [
            //         'Unlimited products',
            //         'Unlimited subscribers',
            //         'Advanced analytics',
            //         '1-hour, dedicated support response time',
            //         'Marketing automations',
            //         'Custom reporting tools',
            //     ],
            //     featured: true,
            //     active: false,
            //     cta: 'Buy plan',
            // },
        ],
    },
];